name: fastapi-ecommerce-prod
services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    # Запускаем сервер Gunicorn
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_NAME}

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: